import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.registeredTools={};Object.defineProperty(document,'modelContext',{value:{registerTool:t=>{window.registeredTools[t.name]=t;}}});});
await page.goto('http://localhost:5173');await page.waitForSelector('.pad');
await page.screenshot({path:'/tmp/keylab-desktop.png',fullPage:true});
await page.click('#audio');await page.waitForFunction(()=>document.querySelector('#audio').textContent.includes('enabled'),null,{timeout:60000});
await page.uncheck('#countin');await page.click('#record');await page.waitForTimeout(200);await page.keyboard.press('a');await page.waitForTimeout(170);await page.keyboard.press('s');await page.waitForTimeout(110);await page.keyboard.press('d');await page.click('#stop');
let p=await page.evaluate(()=>JSON.parse(localStorage.getItem('keylab-project')));assert.equal(p.tracks[0].notes.length,3);const original=p.tracks[0].notes.map(n=>n.start);
await page.click('#quantize');p=await page.evaluate(()=>JSON.parse(localStorage.getItem('keylab-project')));assert.ok(p.tracks[0].notes.every(n=>Math.abs(n.start*4-Math.round(n.start*4))<1e-8));
await page.click('#undo');p=await page.evaluate(()=>JSON.parse(localStorage.getItem('keylab-project')));assert.deepEqual(p.tracks[0].notes.map(n=>n.start),original);
await page.click('#add-track');await page.selectOption('#sound','supersaw');await page.click('#record');await page.waitForTimeout(150);await page.keyboard.down('a');await page.keyboard.down('d');await page.waitForTimeout(360);await page.keyboard.up('a');await page.keyboard.up('d');await page.click('#stop');
p=await page.evaluate(()=>JSON.parse(localStorage.getItem('keylab-project')));assert.equal(p.tracks.length,2);assert.equal(p.tracks[1].notes.length,2);assert.ok(p.tracks[1].notes.every(n=>n.duration>.5));
assert.match(await page.inputValue('#code'),/\.layer\(/);
await page.click('#play');await page.waitForTimeout(300);assert.notEqual(await page.textContent('#position'),'1.1.1');await page.click('#stop');
await page.reload();assert.equal(await page.locator('.track').count(),2);
const tool=await page.evaluate(async()=>{const t=window.registeredTools.read_keylab_project;const result=await t.execute({});let invalid=false;try{t.execute({bad:1});}catch{invalid=true;}return {tracks:result.project.tracks.length,invalid};});assert.deepEqual(tool,{tracks:2,invalid:true});
await page.click('#demo');await page.screenshot({path:'/tmp/keylab-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/keylab-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
assert.deepEqual(errors,[]);console.log('PASS: live sample loading, keyboard recording, held synth chords, playback, quantization, undo, autosave restore, export, WebMCP and mobile layout.');
await browser.close();
