import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {quantizeNotes,validateProject,newTrack,exportStrudel,audibleTracks} from '../core.js';
globalThis.crypto??=webcrypto;
const note=(start,duration=.3,pitch='bd')=>({id:crypto.randomUUID(),start,duration,pitch});
const project=()=>({version:1,bpm:120,bars:2,tracks:[newTrack()]});
test('quantization preserves source notes, wraps near-loop hits, and rounds held lengths',()=>{const ns=[note(.13,.7),note(7.98,.03)];const result=quantizeNotes(ns,.25,8);assert.equal(result[0].start,.25);assert.equal(result[0].duration,.75);assert.equal(result[1].start,0);assert.equal(result[1].duration,.25);assert.equal(ns[0].start,.13);});
test('triplet quantization preserves triplet rhythm',()=>{const out=quantizeNotes([note(.34),note(.65)],1/3,8);assert.ok(Math.abs(out[0].start-1/3)<1e-10);assert.ok(Math.abs(out[1].start-2/3)<1e-10);});
test('project validation rejects bad notes and non-finite or unexpected settings',()=>{const p=project();p.tracks[0].notes=[note(2)];assert.equal(validateProject(p).tracks[0].notes.length,1);for(const value of [-1,8,Infinity]){p.tracks[0].notes[0].start=value;assert.throws(()=>validateProject(p));}p.tracks[0].notes=[];p.bpm=NaN;assert.throws(()=>validateProject(p));p.bpm=120;p.tracks[0].sound='__proto__';assert.throws(()=>validateProject(p));});
test('solo and mute define both playback and export selection',()=>{const a=newTrack(),b=newTrack();b.solo=true;assert.deepEqual(audibleTracks([a,b]),[b]);b.mute=true;assert.deepEqual(audibleTracks([a,b]),[]);});
test('export uses a native sound bank, retains off-grid timing and does not clip drum tails',()=>{const p=project();p.tracks[0].notes=[note(.13)];const out=exportStrudel(p,{'909':{bd:'https://example.com/kick.wav'}});assert.match(out,/setcpm\(30\)/);assert.match(out,/\.slow\(2\)\.late\(0.0325\)/);assert.match(out,/RolandTR909/);assert.doesNotMatch(out,/https:|samples\(/);assert.doesNotMatch(out,/legato/);});
