import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1400,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const editor=page.frameLocator('iframe');
const read=()=>page.evaluate(()=>localStorage.getItem('live-strudel-document-v3'));
const settle=()=>page.waitForFunction(()=>document.body.dataset.busy==='false');
try{
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:5173/');
 await page.waitForSelector('.note');
 assert.equal(await page.locator('.cm-editor').count(),0);
 assert.equal(await editor.locator('.cm-editor').count(),1);
 const code='setcpm(60)\nmelody: note("c4 e4 g4").s("sine").lpf(slider(800,100,2000,1))._pianoroll()';
 await editor.locator('.cm-content').fill(code);await page.waitForTimeout(450);await settle();
 const frame=page.frames().find(f=>f.url().includes('player.html'));
 assert.equal(await frame.evaluate(()=>!!getIsStarted()),false);
 await page.locator('#play').click();await settle();
 assert.equal(await page.locator('#document-state').textContent(),'Playing applied document.');
 await editor.locator('.cm-content [style*="outline:"]').first().waitFor();
 assert.ok(await editor.locator('canvas').count()>0);
 const highlighted=await editor.locator('.cm-content [style*="outline:"]').allTextContents();
 await expect.poll(async()=>(await editor.locator('.cm-content [style*="outline:"]').allTextContents()).join('|')).not.toBe(highlighted.join('|'));
 const painted=await editor.locator('canvas').evaluateAll(cs=>cs.some(c=>c.getContext('2d').getImageData(0,0,c.width,c.height).data.some(v=>v!==0)));
 assert.equal(painted,true);
 await page.screenshot({path:'/tmp/live-strudel-native-editor.png'});
 const slider=editor.locator('.cm-slider input');
 await slider.evaluate(e=>{e.value='1200';e.dispatchEvent(new Event('input',{bubbles:true}));});
 await expect.poll(read).toContain('slider(1200,100,2000,1)');
 await page.waitForFunction(()=>localStorage.getItem('live-strudel-document-v3').includes('slider(1200,100,2000,1)'));
 await editor.locator('.cm-content').focus();await page.keyboard.press('Control+z');
 await expect.poll(read).toBe(code);
 await page.locator('#stop').click();await settle();
 await expect.poll(async()=>editor.locator('.cm-content [style*="outline:"]').count()).toBe(0);
 assert.equal(await frame.evaluate(()=>{try{return parent.document.body.nodeName}catch(e){return e.name}}),'SecurityError');
 await page.locator('#reset').click();
 await expect.poll(read).toBe(code);
 assert.equal(await page.locator('iframe').count(),1);
 assert.deepEqual(errors,[]);
 console.log('PASS native editor, animated highlights, rendered piano-roll widget, source-backed slider, shared undo, stop and sandbox reset');
}finally{await browser.close();}
